### ISSUE TITLE
Support for Comet DECT and FRITZ!DECT 301

### ISSUE THREAD

**Issue by Schnuecks** [tim-hellhake/fritz-adapter#1]
Please support these thermostates.

Like 
https://www.openhab.org/addons/bindings/avmfritz/

**Comment by tim-hellhake** [comment]
Sorry it took me some time to find someone who could borrow me his thermostat.

**Comment by Schnuecks** [comment]
Great, thanks for your answer. It's great to here that's my thred is not forgotten. Thanks ;)

**Comment by tim-hellhake** [comment]
Wow that was quick 😬

**Comment by tim-hellhake** [comment]
Do you have Comet thermostat?

**Comment by tim-hellhake** [comment]
My current implementation accepts only the `DECT 301` thermostat.
I'll try to make it a bit more generic but I need someone to test it.

**Comment by Schnuecks** [comment]
> Do you have Comet thermostat?

Yes, it should work with Comet DECT instead of FRITZ!DECT 300

**Comment by tim-hellhake** [comment]
The new version with thermostat support should be available now.
If you have any problems don't hesitate to open a new issue.
