### ISSUE TITLE
devices found can't set temperature

### ISSUE THREAD

**Issue by Schnuecks** [tim-hellhake/fritz-adapter#2]
hello i tried it today here my current status

name: living room
model: Comet DECT
IPEI: 11960 0007544
version: 03.68
found in webthings
can't change temperature

name: dining room
model: Comet DECT
IPEI: 11795 0740112
version: 03.68
found in webthings
can't change temperature

name: bathroom
model: Comet DECT
IPEI: 11795 1002544
version: 03.68
found in webthings
can't change temperature

name: office
model: Comet DECT
IPEI: 11960 0205688
version: 03.68
found in webthings
can't change temperature

name: child's room
model: Comet DECT
IPEI: 11959 0234728
version: 03.68
found in webthings
can't change temperature

group "living area"
		living room & dining room
not found in webthings

[run-app.log.txt](https://github.com/tim-hellhake/fritz-adapter/files/3587440/run-app.log.txt)

thank for your engagement ;)

**Comment by tim-hellhake** [comment]
I prepared a new release.
With the new version of the adapter, you should be able to activate debug logs in the config.

**Comment by tim-hellhake** [comment]
Ok, that's strange.
According to the log, there are a lot of timeouts to your fritz box.
Is there maybe a problem with the network?

**Comment by Schnuecks** [comment]
Still shows version 0.2.0
Could i trigger the update manually?

**Comment by Schnuecks** [comment]
> Ok, that's strange.
> According to the log, there are a lot of timeouts to your fritz box.
> Is there maybe a problem with the network?

Not so far, seems normal.

the user is resticted to smarthome settings in fritzbox nothing else, eventually this cause the timeout?

**Comment by tim-hellhake** [comment]
> Still shows version 0.2.0

The PR for the update is still open.

**Comment by tim-hellhake** [comment]
`0.2.1` is out

**Comment by Schnuecks** [comment]
Here the new log 
i added a new user with no restriction error stay same
i checked all but all other apps have no problem with the connection, i can read all settings and can switch everthing.

[run-app.log.2019-09-09.txt](https://github.com/tim-hellhake/fritz-adapter/files/3591769/run-app.log.2019-09-09.txt)

**Comment by Schnuecks** [comment]
> `0.2.1` is out

thanks

**Comment by Schnuecks** [comment]
Here two links from avm as additional information
https://avm.de/service/schnittstellen/
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_homeauto.pdf

**Comment by tim-hellhake** [comment]
Maybe the fritz! box does not like the poll interval.

**Comment by tim-hellhake** [comment]
I added a new config option which allows you to set the poll interval.
The default value is 5 seconds.
It was 1 second before.

**Comment by tim-hellhake** [comment]
As soon as the PR is merged you can try the new version.

**Comment by Schnuecks** [comment]
Great, looks good so far.

No fritzbox errors, nice. 
temperature works.

here the log
[run-app.log.2019-09-11.13.txt](https://github.com/tim-hellhake/fritz-adapter/files/3599356/run-app.log.2019-09-11.13.txt)

**Comment by Schnuecks** [comment]
If i could ask for the design a thermostat or a radiator would be nice. a slider in temperature settings too. so far great work.

**Comment by tim-hellhake** [comment]
> Great, looks good so far.

Nice to hear that.

> so far great work

I'm always happy to help.

> If i could ask for the design a thermostat or a radiator would be nice

Unfortunately, there is no thermostat capability in https://iot.mozilla.org/schemas.
There are plans to add it though.
See mozilla-iot/schemas#13 and mozilla-iot/gateway#1629.

> a slider in temperature settings too.

I'll try to add that.
Could you check the minimal and maximal temperature you can set at the comet thermostat for me?

**Comment by Schnuecks** [comment]
Hi, you could temporarily use the icon from the weather addon 😊 unfortunately it won't work. 

the lowest value is 8 the highest 28 

again thanks to you

**Comment by tim-hellhake** [comment]
> you could temporarily use the icon from the weather addon

Generally, the gateway decides which icon to use for a thing based on the capabilities.
I'll have to take a look at the addon to find out which one is responsible for the icon.

> the lowest value is 8 the highest 28

Thanks, I will use that for the limits of the slider.

> again thanks to you

You're welcome.

**Comment by tim-hellhake** [comment]
When the PR is merged the temperature property should have a slider.

**Comment by tim-hellhake** [comment]
With the new update, the temperature property should have a slider.

**Comment by Schnuecks** [comment]
Great work as intended ;)

**Comment by tim-hellhake** [comment]
> you could temporarily use the icon from the weather addon

I played around a little bit, and it seems to be possible, but it makes the temperature property read-only.
There may be changes in the gateway necessary.

**Comment by tim-hellhake** [comment]
The thing bubble now shows the actual temperature and a thermometer icon.
I used the actual temperature because it is read-only anyways.
Would you prefer the set temperature?

I also changed the id and the title of the set temperature property.
You may have to update your rules.

**Comment by tim-hellhake** [comment]
@Schnuecks

**Comment by Schnuecks** [comment]
Great, looks nice.
No, there is no need to set temperature there.
But if you want you can add it.

thanks for all
