### ISSUE TITLE
Feedback / Improvements for Newcomers

### ISSUE THREAD

**Issue by SirFlour** [tim-hellhake/fritz-adapter#6]
Hello Tim, many thanks for the great fritz-adapter. It works perfect with FRITZ!DECT 301.

I struggelt a bit to setup the standard local Frit host info, until i found in the Readme the correct format.

I think it could help others, if you can add these defaultlocal Frit host info http://fritz.box directly in the Adapter Info in the Gateway Config? So that the user just copies it.

Also in the readme, there is ony the FRITZ!DECT 200 under the supportet devices. I think you should also add FRITZ!DECT 301, because it is working as well :)

Many thanks and have a nice day

**Comment by tim-hellhake** [comment]
> It works perfect with FRITZ!DECT 301

Great to hear that!

> I think it could help others, if you can add these defaultlocal Frit host info http://fritz.box directly in the Adapter Info in the Gateway Config

I added it to the description of the host parameter.
After the next update, you should see it in the config menu.

> I think you should also add FRITZ!DECT 301

Added :)

> Many thanks and have a nice day

Thank you very much, I wish you the same :)

**Comment by SirFlour** [comment]
Cool many thanks for your fast reply and direct implementation. 

I am looking forward to the next release :)
