### ISSUE TITLE
Support for FRITZ!DECT 210

### ISSUE THREAD

**Issue by SirFlour** [tim-hellhake/fritz-adapter#7]
Hello Tim, is it possible to include a support for FRITZ!DECT 210? 

I have one at home and it is not recognized as a new thing. I guess because it is not setup in the firtz-adapter.

If possible i am happy to support you. Just let me know. 

Many thanks and have a nice day

**Comment by tim-hellhake** [comment]
> Hello Tim, is it possible to include a support for FRITZ!DECT 210?

Sure! The next update should support it.
Unfortunately, I have no FRITZ!DECT 210, so you need to test it for me.

**Comment by SirFlour** [comment]
Great! I will test it and let you know. Should I provide in this Issue Feedback or should we open then a new issue?

I am looking forward to the next release :)

**Comment by tim-hellhake** [comment]
> Should I provide in this Issue Feedback or should we open then a new issue?

I would say we let the issue open until the problem is resolved.

> I am looking forward to the next release :)

As soon as the linked PR is merged you can test it :)

**Comment by tim-hellhake** [comment]
Which just happened :grimacing:

**Comment by SirFlour** [comment]
Testing Feedback.
 - Update went well. 
 - The default host info is there.
 - FRITZ!DECT 301 is working.
 - FRITZ!DECT 210 is working as well. I can switch it on and off. :)
      Did you also add the Temperature info? This is not showing up.

**Comment by tim-hellhake** [comment]
> FRITZ!DECT 210 is working as well

Nice!

> Did you also add the Temperature info?

Currently, only the thermostats have a temperature property.
Would you mind creating a new issue for the temperature so we can close this one?

**Comment by SirFlour** [comment]
Great :) Done. Many thanks again for the fast and great support :)
