### ISSUE TITLE
add Temperature Support for FRITZ!DECT 210

### ISSUE THREAD

**Issue by SirFlour** [tim-hellhake/fritz-adapter#8]
Please add the Temperature Support for FRITZ!DECT 210

Many thanks and have a nice week :)

**Comment by tim-hellhake** [comment]
![image](https://user-images.githubusercontent.com/17127122/94200852-6a101600-febb-11ea-9730-f1b377f81e66.png)

The next update should contain the temperature.

**Comment by SirFlour** [comment]
cool. i tested it and it is working. shows the exact temperatur as in the fritzbox :)
i guess you can add in the description that the fritz adapter supports the FRITZ!DECT 210 device as well.

many thanks for the fast support and enjoy the weekend!
